### ISSUE TITLE
Front panel design missing?

### ISSUE THREAD

**Issue by trygvelu** [m0xpd/ADSR#1]
Hi - first off, I really appreciate your effort on publishing schematics and background for your projects!
I'm just starting out with building some modules, and have produced a couple of your PCBs (ADSR and VCA). I am just finishing up the builds, after sourcing components. I thought I'd have a go at doing the front panels myself, but use the front panel in the project as a template. But when I open the front panel project in KiCad the schematic is empty.
I'm a novice at using KiCad, but the VCA front panel loads just fine, so I think there might be something off with this front panel project.

**Comment by m0xpd** [comment]
Hi. Thanks for your kind comments.
I see what you mean about the ADSR Front Panel files - I have just uploaded a new set of files describing the same panel, which seem to constitute a complete KiCad project. I hope these will work properly for you. 
Note that the schematics for all the PCBs are intentionally "empty" there is no electrical dimension to these panels.
Please let me know if these changes work for you.
Paul / m0xpd

**Comment by trygvelu** [comment]
Tested, and now the panel comes up just fine in KiCad.
Thanks!
